# Generated by Django 2.2.4 on 2019-08-12 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('present', models.BooleanField(db_index=True, default=False, verbose_name='Present')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('company', models.CharField(max_length=255, verbose_name='Company')),
                ('title', models.CharField(max_length=255, verbose_name='Job title')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Resume', verbose_name='Resume')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('present', models.BooleanField(db_index=True, default=False, verbose_name='Present')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('school', models.CharField(max_length=255, verbose_name='School')),
                ('degree', models.CharField(max_length=255, verbose_name='Degree')),
                ('major', models.CharField(max_length=255, verbose_name='Major')),
                ('topic', models.TextField(verbose_name='Research topics')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Resume', verbose_name='Resume')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
