# Generated by Django 2.2.4 on 2019-08-12 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Resume title')),
                ('description', models.TextField(verbose_name='Resume description')),
                ('primary', models.BooleanField(db_index=True, default=False, verbose_name='Primary resume')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], db_index=True, default=0, verbose_name='Status')),
                ('language', models.IntegerField(choices=[(0, 'Thai'), (1, 'English'), (2, 'Chinese'), (3, 'Japanese'), (4, 'Korean')], db_index=True, default=0, verbose_name='Language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resume',
            },
        ),
    ]
