# Generated by Django 2.2.3 on 2019-08-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneBanned',
        ),
        migrations.AlterModelOptions(
            name='loginlog',
            options={'verbose_name': 'Login log', 'verbose_name_plural': 'Login logs'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterField(
            model_name='emailbanned',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status_memo',
            field=models.CharField(blank=True, max_length=255, verbose_name='User status memo'),
        ),
    ]
