# Generated by Django 2.2.4 on 2019-08-13 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_education_workexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Resume', verbose_name='Resume')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
