# Generated by Django 2.2.4 on 2019-08-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='language',
            field=models.IntegerField(choices=[(0, 'Thai'), (1, 'English'), (2, 'Korean'), (3, 'Chinese'), (4, 'Japanese')], db_index=True, default=0, verbose_name='Language'),
        ),
    ]
