# Generated by Django 2.2.4 on 2019-08-12 16:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20190812_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_no',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
    ]
