# Generated by Django 2.2.4 on 2019-08-12 16:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_resume_resume_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_no',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
