# Generated by Django 2.2.4 on 2019-08-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20190813_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='resume_no',
            new_name='resume_uuid',
        ),
    ]
