# Generated by Django 2.2.3 on 2019-08-06 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, help_text='A short label containing only letters, numbers, underscores or hyphens for URL', max_length=255, unique=True, verbose_name='Slug')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='quest.Category', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255, verbose_name='Problem title')),
                ('content', models.TextField(verbose_name='Problem content')),
                ('input_description', models.TextField(verbose_name='Input description')),
                ('output_description', models.TextField(verbose_name='Output description')),
                ('sample_input', models.TextField(verbose_name='Sample input data')),
                ('sample_output', models.TextField(verbose_name='Sample output data')),
                ('time_limit', models.IntegerField(help_text='Seconds', verbose_name='Time limit')),
                ('memory_limit', models.IntegerField(help_text='MB', verbose_name='Memory limit')),
                ('level', models.IntegerField(db_index=True, verbose_name='Level')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], db_index=True, default=0, verbose_name='Status')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_problem_owned', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quest.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Problem',
                'verbose_name_plural': 'Problems',
            },
        ),
        migrations.CreateModel(
            name='TestSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('input_data', models.TextField(verbose_name='Input data')),
                ('output_data', models.TextField(verbose_name='Output data')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.Problem', verbose_name='Problem')),
            ],
            options={
                'verbose_name': 'Test set',
                'verbose_name_plural': 'Test sets',
            },
        ),
    ]
