# Generated by Django 2.2.4 on 2019-08-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='x', verbose_name='Category description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='language',
            field=models.CharField(default='th', help_text='th|en|ko|cn|ja', max_length=2),
            preserve_default=False,
        ),
    ]
