# Generated by Django 2.2.4 on 2019-08-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytranslation',
            name='language',
            field=models.CharField(choices=[('th', 'Thai'), ('en', 'English'), ('ko', 'Korean'), ('cn', 'Chinese'), ('ja', 'Japanese')], default='th', max_length=2, verbose_name='Language'),
        ),
    ]
