# Generated by Django 2.2.4 on 2019-08-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0002_auto_20190820_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='language',
            field=models.CharField(default='th', help_text='th|en|ko|cn|ja', max_length=2),
        ),
    ]
