# Generated by Django 2.2.4 on 2019-08-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0002_auto_20190820_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], db_index=True, default=1, verbose_name='Level'),
        ),
    ]
