# Generated by Django 2.2.3 on 2019-08-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0002_auto_20190806_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], db_index=True, default=0, verbose_name='Status'),
        ),
    ]
