# Generated by Django 2.2.4 on 2019-08-20 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0002_auto_20190820_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylanguage',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quest.Category', verbose_name='Category'),
            preserve_default=False,
        ),
    ]
