# Generated by Django 2.2.4 on 2019-08-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0003_categorylanguage_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AddField(
            model_name='categorylanguage',
            name='title',
            field=models.CharField(default='', max_length=128, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
