# Generated by Django 2.2.4 on 2019-08-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0004_auto_20190820_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylanguage',
            name='language',
            field=models.CharField(choices=[('th', 'Thai'), ('en', 'English'), ('ko', 'Korean'), ('cn', 'Chinese'), ('ja', 'Japanese')], default='th', max_length=2),
        ),
    ]
