# Generated by Django 2.2.4 on 2019-08-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0005_auto_20190820_1217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryLanguage',
            new_name='CategoryTranslation',
        ),
    ]
