# Generated by Django 2.2.4 on 2019-08-22 09:26

from django.db import migrations
import easy_thumbnails.fields
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=job.models.upload_directory_path, verbose_name='Company logo'),
        ),
    ]
